name: Mark Tower, Artist
markdown: kramdown
timezone: America/Chicago
collections:
    artwork:
      output: true
      permalink: /:collection/:path/


      
# webrick:
#   headers:
#     Access-Control-Allow-Origin: "*" 
#     Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE, OPTIONS'