name: Mark Tower, Artist
markdown: kramdown
timezone: America/Chicago
collections:
    artwork:
      output: true
      permalink: /:collection/:path/

# webserver_headers:
#   "Access-Control-Allow-Origin": "*"